# https://github.com/nextcloud/docker
version: "3.3"

services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: nextcloud
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
  app:
    image: nextcloud
    ports:
      - "8181:8181"
    depends_on:
      - db
    volumes:
      - nextcloud:/var/www/html
    restart: always
    labels:
      - "traefik.backend=nextcloud"
      - "traefik.frontend.rule=Host: nextcloud.ufpa.br"
volumes:
  nextcloud:
  db:
